apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "everything-is-bigger-in-texas"
  annotations:
    "humanitec.com/orgId": "kubecon-na-2024"
    "humanitec.com/appId": "everything-is-bigger-in-texas"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
